default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: abdozayan
  host: localhost

development:
  <<: *default
  database: DataApp-dev

test:
  <<: *default
  database: DataApp-test

production:
  <<: *default
  database: DataApp-prod