default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: developer
  password: supersecretpassword
  host: localhost

development:
  <<: *default
  database: gemstone_blog_dev

test:
  <<: *default
  database: gemstone_blog_test

production:
  <<: *default
  database: gemstone_blog_prod