default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= Rails.application.credentials.postgres[:username] %>
  password: <%= Rails.application.credentials.postgres[:password] %>
  host: localhost

development:
  <<: *default
  database: gemstone_blog_dev

test:
  <<: *default
  database: gemstone_blog_test

production:
  <<: *default
  database: gemstone_blog_prod